formoptimization/crc/compress_clean/ccapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^$',views.home,name='home'),
#	url(r'^(?P<cutoff>.*)-(?P<threshold>.*)-(?P<data_file>.*)-(?P<clustering_func>.*)-(?P<num_groups>.*)',views.viewtree,name='viewtree')
	url(r'^tree',views.viewtree,name='viewtree')
]

formoptimization/crc/compress_clean/compress_clean/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^ccapp/', include('ccapp.urls',namespace='ccapp'))
]

formoptimization/formoptimization/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'formoptimization.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

formoptimization/crc/compress_clean/ccapp/models.py
from django.db import models

# Create your models here.

class InputParam(models.Model):
	param_text=models.CharField(max_length=200)
	def __str__(self):
		return self.param_text
	
class ParamVal(models.Model):
	param_name=models.ForeignKey(InputParam)
	val=models.CharField(max_length=256)
	def __str__(self):
		return self.val

formoptimization/crc/models.py
from django.db import models

class Response(models.Model):
	responseId = models.BigIntegerField(default=0)
	collectorId = models.BigIntegerField(default=0)
	startDate = models.DateTimeField()
	endDate = models.DateTimeField()
	confirm = models.BooleanField()
	metroArea = models.CharField(max_length=256)
	zipCode = models.CharField(max_length=10)
	q1 = models.CharField(max_length=5)
	q2 = models.CharField(max_length=5)
	q3 = models.CharField(max_length=5)
	q4 = models.CharField(max_length=5)
	q5 = models.CharField(max_length=5)
	q6 = models.CharField(max_length=5)
	q7 = models.CharField(max_length=5)
	openEnded = models.CharField(max_length=1024)
	gender = models.CharField(max_length=32)
	age = models.CharField(max_length=32)
	income = models.CharField(max_length=32)
	education = models.CharField(max_length=32)

	class Meta:
		app_label = 'crc'

formoptimization/crc/compress_clean/ccapp/views.py
from django.shortcuts import render
CODE_PATH='$HOME/DocumentsGitHub/dataacquisition/formoptimization/crc'
import sys
sys.path.append(CODE_PATH)
#from tests import get_tree_json

def home(request):
	return render(request,'ccapp/home.html')

def viewtree(request):#,cutoff,threshold,data_file,clustering_func,num_groups):
	tempdict={}
	tempdict['cutoff']=request.POST['cutoff_input']
	tempdict['th']=request.POST['threshold_input']
	tempdict['file_']=request.POST['file_input']
	tempdict['cluster']=request.POST['clustering_input']
	tempdict['groups']=request.POST['groups_input']
	#json=get_tree_json(eval(tempdict['file_']),eval(tempdict['th']),eval(tempdict['cutoff']),eval(tempdict['cluster']),eval(tempdict['groups']))
	return render(request,'ccapp/viewtree.html',tempdict)
# Create your views here.

formoptimization/crc/views.py
# Create your views here.

formoptimization/crc/compress_clean/ccapp/templates/ccapp/home.html
<h1>Input relevant parameters</h1>

<form  action="{% url 'ccapp:viewtree' %}" method='post'>
	{% csrf_token %}
	<input type='text' name='cutoff_input'/>
	<label for='cutoff_input'>Cutoff</label>
	<div></div>
	<div></div>
	
	<input type='text' name='threshold_input'/>
	<label for='threshold_input'>Threshold</label>
	<div></div>
	<div></div>
	
	<input type='text' name='file_input'/>
	<label for='file_input'>file_name</label>
	<div></div>
	<div></div>
	
	<input type='text' name='clustering_input'/>
	<label for='clustering_input'>Clustering Function</label>
	<div></div>
	<div></div>
	
	<input type='text' name='groups_input'/>
	<label for='groups_input'>Number of groups</label>
	<div></div>
	<div></div>
	
	<input type='submit' value='viewtree'/>
</form>